config/routes.rb
ShirtManagementApp::Application.routes.draw do
  resources :vendors

  root "shirts#index"
  get "/search", to: "shirts#search"
  resources :shirts
end

app/models/shirt.rb
class Shirt < ActiveRecord::Base
  validates :name, :description, :image, presence: true
  validates :description, length: { minimum: 10 }
  validates :image, format: { with: /\A\w+.png\z/ }
  belongs_to :vendor

  def self.search_for(query)
    where('name LIKE ? OR description LIKE ?', "%#{query}%", "%#{query}%")
  end
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
  has_many :shirts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/shirts_controller.rb
class ShirtsController < ApplicationController
  before_action :set_shirt, only: [:edit, :show, :update]

  def index
    @shirts = Shirt.all
  end

  def new
    @shirt = Shirt.new
    @vendors = Vendor.all
  end

  def create
    @shirt = Shirt.new(shirt_params)
    if @shirt.save
      redirect_to @shirt
    else
      render 'new'
    end
  end

  def edit
    @vendors = Vendor.all
  end

  def update
    @shirt.update shirt_params
    redirect_to @shirt
  end

  def search
    query = params[:q]
    # Shirt.where('name LIKE %query%')
    # @shirts = Shirt.where('name LIKE ?', "%#{query}%")
    @shirts = Shirt.search_for(query)
    # @shirts = Shirt.where(name: query)
  end

  def show
  end

  private

  def shirt_params
    params.require('shirt').permit(:name, :description, :image, :vendor_id)
  end

  def set_shirt
    @shirt = Shirt.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash.now[:notice] = "Invalid Shirt ID #{params[:id]}"
    redirect_to root_path
  end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  def index
    @vendors = Vendor.all
  end

  def new
    @vendor = Vendor.new
  end

  def create
    vendor_params = params.require(:vendor).permit(:name, :website)
    @vendor = Vendor.new vendor_params
    if @vendor.save
      redirect_to @vendor, notice: "Vendor #{@vendor.name} added to the site"
    else
      render 'new'
    end
  end

  def show
    @vendor = Vendor.find params[:id]
    @shirts = @vendor.shirts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shirts_helper.rb
module ShirtsHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ShirtManagementApp" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">ShirtManagementApp</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Vendors", vendors_path  %></li>
              <li><%= link_to "Shirts", shirts_path  %></li>
              <li><%= link_to "Add a new shirt!", new_shirt_path %></li>
              <li><%= link_to "Add a new vendor!", new_vendor_path %></li>
            </ul>

              <%= render 'shirts/search' %>

          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header" style="font-size:20px;">My Vision</li>
              <p>Over the years, I've collected a whole lot of t-shirts, they're pretty much the only thing I wear. The problem is, I keep them in stacks in a big rack of square cubby-like containers, so I wash them, I fold them, I stack them on top, and then inevitably wind up wearing the same dozen shirts over and over again. I've been trying to devise an ingenious way to get a better rotation...here we go.</p>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/shirts/_form.html.erb
<% if @shirt.errors.any? %>
<h2>There were errors saving your shirt</h2>
<ul>
  <% @shirt.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%= form_for @shirt do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :description %>
<%= f.text_field :description %>
<%= f.label :image %>
<%= f.text_field :image %>
<%= f.collection_select :vendor_id, @vendors, :id, :name %>
<%= f.submit %>
<% end %>

app/views/shirts/_list.html.erb
<ul class="thumbnails">
  <% @shirts.each do |shirt| %>
  <li class="span4" style="margin:0; height: 400px; padding:5px;">
    <div class="thumbnail">
      <%= link_to image_tag(shirt.image), shirt %>
      <h3><%= shirt.name %></h3>
      <h4><%= shirt.description %></h4>
    </div>
  </li>
  <% end %>
</ul>

app/views/shirts/_search.html.erb
<%= form_tag "/search", method: "GET", class: "form-search navbar-search pull-right" do %>
  <div class="input-append">
    <%= search_field_tag :q, "", class: "input-medium search-query" %>
    <%= submit_tag "Search", class: "btn" %>
  </div>
<% end %>

app/views/shirts/edit.html.erb
<h1>Edit Shirt</h1>
<%= render 'form' %>

app/views/shirts/index.html.erb
<h1>Shirt Library</h1>
<p><%= notice %></p>

<%= render "list" %>

app/views/shirts/new.html.erb
<h1>Create a New Shirt</h1>
<%= render 'form' %>

app/views/shirts/search.html.erb
<h1>Results</h1>
<%= render "list" %>
<button class="btn"><%= link_to "Back", shirts_path %></button>

app/views/shirts/show.html.erb
<h1><%= @shirt.name %></h1>
<h2><%= @shirt.description %></h2>
<%= image_tag @shirt.image %>
<h2 style="color:#000000">
Made by: <%= link_to @shirt.vendor.name, vendor_path %>
</h2>
<p>
<button class="btn"><%= link_to "Edit", edit_shirt_path(@shirt) %></button>
<button class="btn"><%= link_to "Back", shirts_path %></button>
</p>

app/views/vendors/index.html.erb
<h1>Vendors</h1>
<ol>
<% @vendors.each do |vendor| %>
 <li><%= link_to vendor.name, vendor %></li>
 <p style="color:#ff0054">Find us at <%= link_to vendor.website, vendor.website %></p>
<% end %>
</ol>

app/views/vendors/new.html.erb
<h1>New Vendor</h1>
<fieldset>
  <%= form_for @vendor do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :website %>
    <%= f.text_field :website %>
    <%= f.submit %>
  <% end %>
</fieldset>

app/views/vendors/show.html.erb
<h1><%= link_to @vendor.name, @vendor.website %></h1>
<h2>Shirts on the site include:</h2>

<ul class="thumbnails">
  <% @shirts.each do |shirt| %>
  <li class="span4" style="margin:0; height: 400px; padding:5px;">
    <div class="thumbnail">
      <%= link_to image_tag(shirt.image), shirt %>
      <h3><%= shirt.name %></h3>
      <h4><%= shirt.description %></h4>
    </div>
  </li>
  <% end %>
</ul>